:PROPERTIES:
:ID:       0f1309a6-2abe-4a53-b9b1-08b480d55ca6
:END:
#+title: Medicine

* Antidepressants

** Fluoxetine (sold under brand name Prozac)

It is approved for the treatment of major depressive disorder (MDD), obsessive compulsive disorder (OCD), panic disorder, bulimia nervosa, and premenstrual dysphoric disorder (PMDD).

Dosage: 20mg Per day for Adults. 10mg for Children.

If you stop taking fluoxetine suddenly, you may get withdrawal symptoms such as:

1. Feeling dizzy
2. Feeling sick
3. Numbness or tingling in the hands or feet
4. Trouble sleeping
5. Feeling agitated or anxious
6. Headaches
7. Shaking

Taking too much can cause symptoms such as:

1. Being sick (vomiting)
2. Shaking
3. Feeling sleepy
4. Feeling agitated
5. Feeling dizzy
6. Racing heart
7. Fits or Seizures

*** Common Side Effects and how to deal with them

Feeling sick - Try taking it with or after a meal. Avoid rich or spicy food if need be.

Headaches - Rest and drink plenty of fluids. Should go away after a week.

Can't sleep - Take it in the morning.

Diarrhoea - Drink plenty of fluids. Don't take any meds for it without consulting a pharmacist or doctor.

Feeling tired or weak - Stop what your doing and sit or lie down until you feel better. No driving or using of machinery if fatigued.

*** Rare Side Effects

It happens rarely (in less than 1 in 100 people), but some people may have serious side effects when taking fluoxetine.

Book an appointment with your doctor if you:

1. Gain weight gain or lose weight without trying
2. Get changes in your periods such as heavy bleeding, spotting, or bleeding between periods

Call a doctor or call 111 straight away if you:

1. Get feelings of overwhelming happiness (euphoria), excessive enthusiasm or excitement, or a feeling of restlessness that means you cannot sit or stand still
2. Are bleeding from the gums or get bruises that appear without a reason or that get bigger
3. Are coughing up blood, or have blood in your pee
4. Have black or red poo, or blood in your vomit – these can be signs of bleeding in your stomach


** St John's Wort

*** Overview 

A herbal medicine used to treat mental health problems. The botanical name for St John's wort is Hypericum perforatum, and it is sometimes marketed and sold as 'Hypericum'. It contains many active substances, including hypericin and hyperforin, which are thought to affect mood.

Studies show that the side effects from St John's Wort are fewer and less severe than those perscribed antidepressant meds. There are also cases of people with 0 side effects at all. But some common side effects include.

1. Feeling nauseous or vomiting.
2. Headaches
3. Allergic reactions
4. Tiredness, dizzyness, confusion etc.
5. Dry mouth
6. Increased sensitivty to sunlight

Some research shows that St John's Wort can increase the symptons of psychosis in those who have bipolar disorder or schizophrenia.

For severe depression however it is shown to have little effect and there is very little evidence to show that it can treat anxiety or seasonal affective disoarder (SAD). It can even make anxiety worse.

*** Dosages 

St John's wort is sold in a variety of different forms. The dosages available vary depending on the form and brand that you buy. It is most commonly sold as tablets and capsules. You can also get it as a tea, or as a liquid called a 'tincture', which you can take as drops in water.

All medicines carry levels of risk in different circumstances, and can affect people in different ways. There is no standard recommended dosage of St John's wort in the UK and it is not currently clear what dosage works best. 

Consut to your doctor or pharmacist and get their reccomendations. Make sure you know how strong the product is and follow the directions on the package.

On the packaging of some products it might refer to the amount of St John's wort as 'aerial parts'. This just means the parts of the plant that grow above the ground.

St John's wort has significant interactions with a large number of medicines which are in common use.

This means that it may affect the way the body processes other medications, which may make them less effective, or increase the chances of harmful side effects. These medications include both prescribed drugs and medicines that you can buy for yourself over the counter.


* Psychosis

** Hallucinations

Hallucinations include:

1. Seeing things that are not there (peoples faces, animals, religious figures etc)
2. Seeing objects in a distorted way
3. Experiencing tates, smells and sensations that have no reason to be there. E.G: Feeling insects crawl on your skin.
4. Hearing voices. (Positive, helpful or nasty)

** Delusions

Contrary to a belief that people just don't share, a delusion is something that nobody else shares and which other experiences have proven to be untrue. They feel completely real to you when you experience them however.

An example being you may think you are rich and powerful or that you can control elements out of your control. These are sometimes called 'delusions of grandeur'

Some delusions can be very frightening and can make you feel threatened or unsafe. For example, you might feel that something or someone is trying to control, harm or kill you (even when you have no reason to believe this). These ideas are sometimes called paranoid delusions.

** Disorganised thinking and speaking

Sometimes called 'formal thought disorder' can be a very specific type of psychosis.

Some terms used to describe what these can be include: 

1. Racing thoughts is when your thoughts go through your head very fast. It can involve them racing so fast that they feel out of control.
2. Flight of ideas is where your thoughts move very quickly from idea to idea, making links and seeing meaning between things that other people don't.

Many people find that they experience racing thoughts and flight of ideas at the same time. If you have disorganised thinking you might:

1. Speak very quickly and stumble over your words so that other people may find it difficult to understand what you're saying
2. Link words together because of the way they sound rather than what they mean, which can make your speech sound jumbled to other people (this is sometimes called word salad)
3. Change the topic of conversation very quickly as your thoughts move from one thing to another
4. Find it difficult to keep your attention on one thing.
 
** What causes Psychosis

The cause of Psychosis is different for everybody, however it could be triggered by a number of things including:

1. Psychical illness or injury
2. Abuse or trauma
3. Recreational drugs (especially cannabis or LSD)
4. Alchohol or smoking 
5. Perscribed Meds
6. Hunger (You may experience hallucinations if you are very hungry, have low blood sugar or if you are not getting enough food.)
7. Lack of sleep
8. Bereavement
9. Genetic inhertiance 


* Paranoia 

Can be a type of delusion, it is when you feel or think you are being threatened despite no evidence showing this.

*** Common things you would be paranoid about 

1. Being talked behind your back
2. Other people trying to make you look bad
3. At the risk of being harmed or even killed
4. People are using hints and double meanings to secretly threaten you or make you feel bad
5. Other people are deliberately trying to upset or irritate you
6. People are trying to take your money or goods.
7. Your actions/thoughts are being interfered with by others
8. You are being controlled or that the goverment is targeting you

*** What counts as a paranoid thought

It is easy to confuse a suspicous thought with a paranoid thought. However suspicous thoughts are more likely to be paranoid if:

1. No one else shares the thought
2. There is no definite evidence for the suspicous thought
3. There is evidence against the suspicous thought
4. It is unlikely you would be singled out
5. You still have suspicious thoughts despite reassurance from others
6. Your suspicions are based on feelings and ambiguous events 

*** What about justified paranoia

For example, if lots of people have been mugged on your street, it is not paranoid to think that you might be mugged too and take care when walking through your area. Justified suspicions can help keep you safe. Evidence and justification can be lots of different things. Your evidence might be an individual experience but it might be a history of persecution or discrimination. For example, if you are a young black man and you know that police target more young black men for stop and search, it's not paranoid to feel under greater threat of a stop and search yourself.

*** Is it a mental health problem

It is a symptom of some mental health problems rather than a standalone diagnosis. Paranoid thoughts can range from mild to very severe and this depends on how much you: 

1. Believe the paranoid thought
2. You think about the paranoid thought
3. You let them upset you 
4. They interfere with everyday life

Lots of people (even up to a third of us) experience mild paranoia at some point in their lives, this is usually non-clinical and the thoughts often go away or change over time once you realise they are not justified or stop having that thought.
However on the other side of things is a very severe paranoia (also called clinical paranoia or persecutory delusions)

Paranoia can be a sympton of:

1. Paranoid Schizophrenia 
2. Delusional Disorder (persecutory type) – a type of psychosis where you have one main delusion related to being harmed by others
3. Paranoid Personality Disorder 


* Personality Disorders 

** Suspicous 

*** Paranoid personality disorder

You may find it hard to: 

1. Confide in people, even your friends and family
2. Find it very difficult to trust people
3. Have difficulty relaxing 
4. Read threats and danger (which others don't see) into everyday situations, innocent remarks or casual looks from others.

*** Schizoid personality disorder

Many people with schizoid personality disorder are able to function fairly well. However unlike in schizophrenia or schizoaffective disorder, you would not usually have psychotic symptoms. However, as a result of the thoughts and feelings associated with this diagnosis you may:


1. Find difficulty forming close relationships with other people
2. Choose to live your life without interference from others
3. Prefer to be alone with your own thoughts
4. Not experience pleasure from many activities
5. Have little interest in sex or intimacy
6. Have difficulty relating to or are emotionally cold towards others.

*** Schizotypal personality disorder

Everyone has their own eccentricities or awkward behaviours. But if your patterns of thinking and behaving make relating to others very difficult, you may receive a diagnosis of schizotypal personality disorder. Unlike in schizophrenia, you usually would not experience psychosis. However, you may:

1. Have distorted thoughts or perceptions

2. Find making and maintaining close relationships extremely difficult

3. Social Anhedonia: Individuals with STPD may have difficulty experiencing pleasure from social interactions or forming close relationships. They might prefer to be alone or engage in activities that do not involve interpersonal connections

4. Odd or Tangential Speech: People with STPD might engage in speech that is difficult to follow due to its tangential or vague nature. Their conversations may jump between unrelated topics or include excessive use of metaphors

5. Paranoia or Suspiciousness: People with STPD may experience mild paranoid thoughts or suspiciousness toward others. They might be particularly sensitive to perceived slights or criticism.

6. Limited Emotional Expression: Individuals with STPD might have a flattened affect, which means their facial expressions and emotional responses can be restricted or less expressive than what is typical.

7. Social Anxiety: Individuals with STPD may experience anxiety in social situations due to their discomfort with social norms and interactions.

8. Inappropriate or Constricted Affect: People with STPD may exhibit emotional responses that are perceived as inappropriate for the situation, or they might show a restricted range of emotional expression.

9. Excessive Social Anxiety: Individuals with STPD may experience intense anxiety in social situations, which can further contribute to their social isolation.


** Emotional and impulsive

*** Antisocial personality disorder (ASPD or APD)

It is natural to sometimes put our own needs, pleasure or personal gain before those of others around us. However, if these actions occur very frequently and you struggle to keep stability in your life, or you regularly act impulsively out of anger or lack of consideration for others, this could lead to a diagnosis of antisocial personality disorder.

Symtoms may include: 

1. Put yourself in dangerous or risky situations, often without thinking
2. Dangerous behavious, sometimes illegal
3. Unpleasant behaviour for others
4. Feel very easily bored and act on impulse – for example, you may find it difficult to hold down a job for long
5. Behave aggressively and get into fights easily
6. Do things even though they may hurt people – to get what you want, putting your needs and desires above other people's
7. Have problems with empathy – for example, you may not feel or show any sense of guilt if you have mistreated others

*** Borderline personality Disorder (BPD)

Borderline personality disorder (BPD) is also known as emotionally unstable personality disorder (EUPD).

We can all experience difficulties with our relationships, self-image and emotions. But you might get a diagnosis of BPD/EUPD if these feel consistently unstable or intense and cause you significant problems in daily life.

Symptoms may include:

1. Feeling worried about people abandoning you, and either do anything to stop that happening or push them away
2. Intense emotions that change quickly. Feeling very high and confident in the morning to low and sad in the afternoon.
3. Not a strong sense of who you are
4. Hard to make or keep stable relationships
5. Act impulsively and do things that could harm you (such as binge eating, using drugs or driving dangerously)
6. Suicidal or self harm thoughts 
7. Feeling empty or lonely a lot
8. Get very angry and struggle to control it
9. Struggle to trust other people
10. Experience other mental health problems alongside BPD, including anxiety, depression, eating problems and post-traumatic stress disorder

BPD is currently the most commonly diagnosed personality disorder.

*** Histrionic personality disorder (HPD)

Most people enjoy being given compliments or positive feedback about their actions. But if you depend very heavily on being noticed, or are seeking approval so much that this affects your day-to-day living, you might get a diagnosis of histrionic personality disorder.

Symptoms may include:

1. Feel uncomfortable if you are not the centre of attention
2. Feel that you have to entertain people
3. Constantly seek, or feel dependent on, the approval of others
make rash decisions
4. Flirt or behave/dress provocatively to ensure that you remain the centre of attention
5. Get a reputation for being dramatic and overemotional
6. Be easily influenced by others.

*** Narcissistic personality disorder (NPD)

It is human nature to be aware of our own needs, to express them, and to want others to be aware of our abilities and achievements, and this is not a bad thing. However once these thoughts become extreme and cause problems then a medical diagnosis may be required.

Symptoms may include:

1. Belief that there are special reasons that make you different, better or more deserving than others
2. Have fragile self esteem, you rely on others to recognise your worth and needs
3. Feel upset if people ingore you and don't give you what you feel you deserve
4. Resent other peoples successes
5. Put your own needs above other people's and expect them to as well
6. Be seen as selfish or unaware of peoples needs



** Anxious 

*** Avoidant personality disorder (AvPD)

We all have things, places or people we don't like, or which make us anxious. But if these things cause so much anxiety that you struggle to maintain relationships in your life, you may get a diagnosis of avoidant personality disorder (sometimes also called anxious personality disorder).

Symptoms may include:

1. Avoid work or social places that mean you'll be with others
2. Expect disapproval and criticism and be very sensitive to it
3. Worry constantly about being 'found out' and rejected
4. Worry about being ridiculed or shamed by others
5. Avoid relationships, friendships and intimacy because you fear rejection
6. Feel lonely and isolated, and inferior to others
7. Be reluctant to try new activities in case you embarrass yourself.

*** Dependant personality disorder (DPD)

We depend on people as part of our lives, this is normal.A healthy balance involves being able to both depend on others as well as being independent from others sometimes, however if these feelings and thoughts impact your daily life and descisions then you may get a DPD diagnosis.

Symptoms may include: 

1. Feeling needy or 'weak' and unable to make descicions or function without others support or help
2. Allow others to take responsibility for many areas in your life
3. Agree to things you feel are wrong or you dislike to avoid being alone or losing someone's support
4. Very fearful of being left to fend for yourself
5. Low self-confidence 
6. See others of being much more capable than you are

*** Obsessive-compulsive personality disorder (OCPD)

 This is seperate from OCD, instead of describing a behaviour it does so a personality

Symptoms may include: 

1. Need to keep everything in order and under control
2. Set unrealistically high standards for yourself and others
3. Think yours is the best way of doing things
4. Worry about you or others making mistakes
5. Feel very anxious if things aren't 'perfect'



* OCD 

** What is it

OCD Can be split into two main parts:

1. Obsessions

These can be unwelcome thoughts, worries or doubts that come to mind repeatedly.

2. Compulsions

Are activities you do to reduce the anxiety caused by obsessions. Such as repeatedly checking a door to make sure it's locked

** To live with it

1. Can disrupt your day to day life, can make it very hard to concentrate 

2. Impact your relationships, you may feel the need to hide your OCD from people close to you

3. Feeling ashamed or lonely, you may feel ashamed of your obsessive thoughts, or worry that they can't be treated. You might want to hide this part of you from other people, and find it hard to be around people or to go outside

4. Feeling anxious, you may find that your obsessions and compulsions are making you feel anxious and stressed. For example, some people feel that they have to carry out their compulsions so frequently that they have little control over them.

** Types of obsessions 

1. Worrying about something you may of said, times can range from days to years ago

2. Worrying your going to harm someone because you will lose control. For example, that you will push someone in front of a train or stab them.

3. Violent or intrusive thoughts or images of yourself doing something violent or abusive

4. Relationship intrusive thoughts often appear as doubts about whether a relationship is right or whether you or your partner's feelings are strong enough. They might lead you to end your relationship to get rid of the doubt and anxiety.

5. Contamination (dirt, germs)

6. Mental contamination. You might experience feelings of dirtiness that are triggered by a person who has harmed you in some way.

7. You might have a fear that something bad will happen if everything isn't 'right'. For example if things are not clean, in order or symmetrical.

** Types of compulsions

*** Rituals 

1. Washing your hands, body, other things often and excessively

2. Touchings things or objects in a certian order or at a particular time

3. Arranging objects in a particular way

*** Checking

1. Checking doors/windows etc to make sure they are locked

2. Check yourself or your clothes for contamination

3. Checking your body to see how it responds to intrusive thoughts

4. Check your memory to make sure an intrusive thought didn't actually happen

*** Correcting thoughts

1. Repeating a word, name or a phrase in your head or out loud

2. Counting to a certian number

3. Replacing an intrusive thought with a different image

*** Reassurance 

1. Repeatedly asking other people to tell you that everything is alright.

** Pure O

Pure O means, 'purely obsessional'. People sometimes use this phrase to describe a type of OCD where they experience distressing intrusive thoughts but there are no external signs of compulsions. However this does not mean there are no compulsions at all.

Pure O still entails mental compulsions but you may not be aware of them as they are not as obvious as physical compulsions.

Some examples of internal compulsions include:

1. Checking how you feel (do you still love your partner)

2. Checking how you feel about a thought (check if you are still upset about it) 

3. Repeating certian phrases or numbers in your head

4. Checking if you still have a thought - for example, first thing in the morning

** Treatment for OCD

*** Cognitive behavioural therapy (CBT)

Cognitive behavioural therapy (CBT) focuses on how your thoughts, beliefs and attitudes affect your feelings and behaviour

*** Exposure and response prevention (ERP)

ERP is a specific prevention for OCD. It encourages you to confront your obsessions and resist your compulsions.

During ERP, your therapist will support you to deliberately put yourself in a situation that would usually make you feel anxious. Instead of performing your usual compulsion, you will be encouraged to try and tolerate the anxiety.

ERP helps you to see that the uncomfortable feelings will eventually go away even if you don't perform a compulsion.

This type of therapy can be challenging and might make you feel more anxious at first. It may help to talk to a healthcare professional before you start ERP. They can answer any questions you have about what it involves, and whether you are in a good place to start the therapy.

*** Cognitive therapy 

Cognitive therapy focuses on identifying and changing negative feelings about yourself, to help you change unhelpful responses and behaviours.

** Medication for OCD

You may be offered the following medications as a standalone treatment or alongside therapy.

*** Selective serotonin reuptake inhibitors (SSRIs)

About SSRIs:

    SSRIs mainly work by blocking the reuptake of serotonin into the nerve cell that released it. This means that the serotonin acts for longer on your brain and body.
    You may find the side effects of SSRIs easier to cope with than with other antidepressants. But these effects can still feel unpleasant, especially when you first start taking the drugs.
    SSRIs are the most commonly prescribed type of antidepressant in the UK.

*** Clomipramine

A tricyclic antidepressant, which you may be offered if an SSRI doesn't work.

About tricyclics:

    Like SNRIs, tricyclics affect your reuptake of noradrenaline and serotonin, making their effects on your brain and body last longer.
    But tricyclics also affect some other chemicals in your body. This can mean they’re more likely to cause unpleasant side effects than other antidepressants.
    They're called 'tricyclic' because of their chemical structure, which has three rings.

** Family members/close friends and what they can do

1. Educate themselves about OCD 

2. Display patience, Recovery from OCD takes time and effort. Be patient and understanding as your family member goes through the treatment process

3. Offer Emotional Support: Let your family member know that you are there to listen without judgment. Offer a supportive and non-critical environment for them to express their feelings and experiences

4. Avoid Accommodation: While it might be tempting to help with compulsions, such as checking rituals or reassurance-seeking, avoid accommodating their OCD behaviors. Accommodation can inadvertently reinforce the disorder

5. Practice Compassion: Remember that the distress and anxiety your family member experiences due to OCD are real. Be compassionate and validate their feelings

6. Reduce Stressors: Minimize unnecessary stressors in their environment, as stress can exacerbate OCD symptoms

7. Model Healthy Coping: Demonstrate healthy coping mechanisms in your own life. This can positively influence their approach to managing anxiety and stress

8. Celebrate Progress: Acknowledge and celebrate even small steps of progress in their journey towards managing OCD
